import { type NextPage } from "next";
import Head from "next/head";
import Todos from "~/components/todo/Todos";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#022f6d] to-[#16152c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            To<span className="text-blue-500">do</span> App
          </h1>
          <div className="flex text-white">
            <Todos />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
